### ISSUE TITLE
CRAN Availability

### ISSUE THREAD

**Issue by jdonnell01** [nik01010/dashboardthemes#20]
Hello,

Are you planning to make this package available via CRAN? I have an internal CRAN mirror configured so I can only consume packages from CRAN, not ancillary github repos.

Thank you,
John

**Comment by nik01010** [comment]
Hi John,
There are currently no plans for a CRAN release, due to the amount of time/effort that would require to maintain. I believe some developers have package repositories that mirror CRAN, as well as repositories for "internally developed packages" - perhaps you could download the latest release for this package from GitHub and add it manually to such a repo.
