### ISSUE TITLE
dashboardthemes with shinydashboardplus

### ISSUE THREAD

**Issue by iadjali** [nik01010/dashboardthemes#33]
Hi, this looks fantastic! Just a question: I tend to work with shinydashboardplus more often these days. Is the dashboardthemes package compatible with shinydashboardplus? If not are there any plans to make a version that is compatible?
Many thanks

**Comment by nik01010** [comment]
Thanks for your question. I have never really used the other available extensions like shinyDashboardPlus etc., and only planned to support the main shinydashboard package due to time availability. However if you notice a particularly strong problem when using the "plus" package, feel free to create another Issue on this repo and I can investigate depending on the scope of it.
Many thanks
