### ISSUE TITLE
compatibility with bs4Dash

### ISSUE THREAD

**Issue by gacolitti** [nik01010/dashboardthemes#42]
I don't think this package is compatible with `bs4Dash` but it is compatible with `shinydashboardPlus`. Any reason why?

For example, adding this to UI does not work:

`dashboardBody(dashboardthemes::shinyDashboardThemes(theme = "blue_gradient"))`

**Comment by nik01010** [comment]
Thanks for your question. I have never really used the other available extensions like shinyDashboardPlus, bs4Dash etc., and only planned to support the main shinydashboard package due to time availability. I think the support for shinyDashboardPlus is only accidental because of how similar it is to the main package from RStudio.
I believe there are other options for theming bs4Dash that you can use, however.
