### ISSUE TITLE
selectInput color on hover

### ISSUE THREAD

**Issue by gacolitti** [nik01010/dashboardthemes#43]
Would be nice to be able to control the background color on hover when selecting from `selectInput()`. Currently, there is no indication which item the cursor is hovering over.

**Comment by nik01010** [comment]
Are you referring to the background colour of the highlighted item (e.g. "Option 2" in the screenshot below)?
It looks like there is a background colour shown on hover, so that looks fine?

![image](https://user-images.githubusercontent.com/37037006/160231692-73a47526-106b-4819-9fa5-ba50a61f5b56.png)

**Comment by gacolitti** [comment]
Turns out it was an issue with the color settings of my display. I fixed it by adjusting my display color settings. Thank you!
