### ISSUE TITLE
Problem with DT

### ISSUE THREAD

**Issue by vikram-rawat** [nik01010/dashboardthemes#5]
![image](https://user-images.githubusercontent.com/22342596/39033151-4cddb1b2-448e-11e8-95ce-cfaaa8d29c48.png)
![image](https://user-images.githubusercontent.com/22342596/39033158-56c62db2-448e-11e8-866f-c31f7a1168c4.png)

I don't see the previous and Next button in grey dark theme. Let me know if it's just me or everybody has the same problem.

**Comment by nik01010** [comment]
This issue happens when the homepage of your dashboard doesn't include a visible datatable object when you first load the app.

In this first screenshot, I set the bottom right TabBox to show the 'First tab' by default. After loading the app and selecting the 'Second tab', I got the same problem as you - couldn't see a Next buttom in my table:
https://ibb.co/n8T1Wn

I managed to fix the issue by setting the TabBox to show the 'Second tab' by default. This meant that when opening the dashboard, there was a dataTable object for the css formatting to be applied to. You'll find in that case, your tables throughout the whole app will show a Next button as well:
https://ibb.co/h1boBn

This was something I tried to improve previously, but have had no luck. It seems like a general issue of applying css in Shiny apps.

**Comment by vikram-rawat** [comment]
https://community.rstudio.com/t/best-way-to-dbdisconnect-in-shiny/7499


This is where I have posted my entire code. You could see that I actually want to load the table on a certain condition and want remove it one I upload it in the database and this could go on and on...


Do you think if I will make the 2 page as my default page it will be solved. If yes I would love to try it.

**Comment by nik01010** [comment]
The background loading and processing tables shouldn't make a difference. I agree, try to make the page where your table is shown the app's default page to quickly test if that fixes the issue. If so, I would suggest making your actual homepage include a small dataTable - for example a summary table with key indicators. That would ensure dataTables are properly formatted throughout the whole app.
